Add controllers and models. Test validation ok
MR-k0f31n/java-filmorate pull request #4
Opened 2023-02-14 13:38 UTC by MR-k0f31n

<ADD> CONTROLLERS USERCONTROLLER, FILMCONTROLLER
<ADD> ADD VALIDATION
<ADD> TEST VALIDATION

2023-02-14 16:48 UTC, TomattmanYandex requested changes
хорошая работа, есть всякие мелочи на поправить, плюс стоит добавить тест на валидацию фильмов, а не только пользователя, плюс можно немного расширить тесты, чтобы проверять не только что есть ошибка но и какая

2023-02-14 16:48 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        checkFilm(film);
лучше бы назвать метод validate

2023-02-14 16:48 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    private final Set<String> usageEmail = new HashSet<>();
хорошрий вариант, но не очень надежный, так как если забудешь при добавлении добавить сюда то логика сломается (а еще пока что вроде как не было такого условия, как минимум в задании

2023-02-14 16:48 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    public User createUser(@Valid @RequestBody User user) throws ValidationException {
зачем throws для RuntimeException

2023-02-14 16:48 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    public User createUser(@Valid @RequestBody User user) throws ValidationException {
В других местах это тоже стоит проверить

2023-02-14 16:48 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        users.put(user.getId(), user);
в этом методе может быть заменен email и это никак не будет замечено (но так как это не было частью задания, исправлять не обязательно)

2023-02-14 16:48 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private int id;
лучше использовать класс обертку вместо примитива

2023-02-14 16:48 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private final int duration;
и тут тоже лучше класс обертка

2023-02-14 16:48 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +
лишние пустые строки

2023-02-14 16:48 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private int id;
снова примитив

2023-02-14 16:48 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @Pattern(message = "Поле login должно содежать только A-Z и 1-0",
такого условия тоже не было, но это на твое усмотрение

2023-02-14 16:48 UTC, TomattmanYandex commented on src/test/java/ru/yandex/practicum/filmorate/validations/UserValidatorTest.java
> +    public void UserNotValidEmail_isValidFalse() {
методы именуем с маленькой буквы

2023-02-14 17:04 UTC, MR-k0f31n commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    private final Set<String> usageEmail = new HashSet<>();
Честно, я много проверок хотел замутить  как у реальной программы) но после мейла я чет подумал что наверно пока не надо, потому что дальше наверное будет еще разделение на получение по id и прочее прочее

2023-02-14 17:25 UTC, MR-k0f31n commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @Pattern(message = "Поле login должно содежать только A-Z и 1-0",
Суровое изучение суровые методы)) для практики ты еще не видел что я натворил в анотации емейла прежде чем понял что она сама по себе работает))

2023-02-14 19:17 UTC, MR-k0f31n reviewed
Все замечания исправлены. в классах поправлены throw, тесты расширены и теперь точно смотрят в сообщениях об ошибках валидации

2023-02-14 19:18 UTC, MR-k0f31n commented
Все замечания исправлены. в классах поправлены throw, тесты расширены и теперь точно смотрят в сообщениях об ошибках валидации

мерджить будем из controllers-films-users в main

2023-02-15 17:02 UTC, TomattmanYandex approved these changes
Отлично

2023-02-15 18:35 UTC, merged