Add friends likes
MR-k0f31n/java-filmorate pull request #5
Opened 2023-02-26 11:06 UTC by MR-k0f31n

Добавлены списки друзей в сущности пользователей
Добавлены списки "лайков" в сущности друзей
Добавлены эндпонты к запросам "Получить пользователя по ИД", "Получить список всех пользователей", "Получить список друзей пользователя", "Получить общих друзей с пользователем"
Добавлены эндпонты к запросам "Получить фильм по ИД", "Получить список всех фильмов", "Получить топ фильмов"
Добавить сервис добавления\Удаления в друзья, поиск общих друзей
Добавить сервис добавления\удаления лайков, получение топ фильмов 
Добавить компоненты хранения пользователей
Добавить компоненты хранения фильмов

2023-02-26 14:47 UTC, TomattmanYandex requested changes
Не понятно почему контроллеры были перемещены в другой пакет, но ладно
Отличная работа, пара небольших изменений и будет все ок

2023-02-26 14:47 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public Map<String, String> handleNullPointerException(final NullPointerException exception) {
хороший момент, но такие обработчики делать не обязательно, у спринга есть встроенные обработчики ошибок, и они делают примерно то же что и этот метод

2023-02-26 14:47 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController (FilmService service) {
можно добавить аннотацию RequiredArgsConstructor Она создаст точно такой же конструктор очень удобно для дальнейшего расширения класса, при добавлении зависимостей не нужно будет дополнительно менять конструктор

2023-02-26 14:47 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private final Set<Integer> userLike = new HashSet<>();
отлично что использован set а не list

2023-02-26 14:47 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +public class FilmService {
В этот класс хорошо было бы добавить зависимость от UserService или UserStorage и при лайках проверять, есть ли такой юзер

2023-02-26 14:47 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                .stream().filter(userStorage.getUserById(otherId).getFriends()::contains)
лучше вынести получение второго пользователя из стрима, явная оптимизация не надо будет нессколько раз пытаться получить одного и того же пользователя

2023-02-26 15:07 UTC, MR-k0f31n commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public Map<String, String> handleNullPointerException(final NullPointerException exception) {
Не очень понял, тут же получается как нас и учили либо отдельный респонс делать либо можно обработать так и указать какой именно код сервер должен ответь. я так и сделал

2023-02-26 15:08 UTC, MR-k0f31n commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController (FilmService service) {
ооо тут были отдельные пляски, я тупой бошка подай пирожка в контроллере использовал разные переменные пути и имена переменных, а ругал во всем компоненты и сервисы, согласен, заменю.

2023-02-26 15:09 UTC, MR-k0f31n commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private final Set<Integer> userLike = new HashSet<>();
изначально хотел сделать List с проверкой есть нету и всего один метод, если пользователя нет значит лайк если пользователь уже лайкал - значит ремув лайк, но не знаю насколько это верно было бы, поэтому через сет бороться начал

2023-02-26 15:11 UTC, MR-k0f31n commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +public class FilmService {
у меня была идея еще и фильмы юзеру записывать, а потом подумал, а надо до ли?

2023-02-26 15:18 UTC, MR-k0f31n commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +public class FilmService {
если в дальнейшем конечно поставять задачу записывать и выводить список понравившегося пользоваетлю

2023-02-26 15:19 UTC, MR-k0f31n commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                .stream().filter(userStorage.getUserById(otherId).getFriends()::contains)
Тоже думал что и конструкция громадная и явные проблемы, но это первые пробы стримов лямбд =) как хорошо что у меня ревью ткнет куда нужно

2023-02-26 15:31 UTC, MR-k0f31n reviewed
<FIX> Исправить - проверку наличие пользователя при постановке лайка.
Исправить - оптимизация получения списка общих друзей.
Исправить - автоматическа анотация добовления зависимостей в контруктор.

2023-02-27 09:48 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                .stream().filter(userStorage.getUserById(otherId).getFriends()::contains)
не сама конструкция, только то, что получаешь из хранилища в самом стриме, если у тебя будет у кого то 10 друзей, то второго пользователя, одного и того же, получим 10 раз

2023-02-27 09:50 UTC, TomattmanYandex approved these changes
Принято

2023-02-27 09:50 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +public class FilmService {
пока не надо усложнять, как доберетесь до баз данных, все изменится, и придётся все равно переделывать

2023-02-27 10:27 UTC, merged