Добавить дата базу, добавить новую логику "рейтинги фильмов" \ "мировой возрастной рейтинг"
MR-k0f31n/java-filmorate pull request #9
Opened 2023-03-30 20:21 UTC by MR-k0f31n

перенести все хранение на dataBase 
все запросы через sql запросы
новые классы: MPA, Rating

2023-03-31 11:58 UTC, TomattmanYandex requested changes
Привет, коменты в пулл реквесте, схему надо делать именно базы данных а не классов, я из-за этого чуть без проверки всего остального не отправил на переделку весь пулл реквест, так же нужны интеграционные тесты на слой базы данных

2023-03-31 11:58 UTC, TomattmanYandex commented on DataBase.png
схему надо исправить
1) в фильмах не надо хранить сет id жанров это хранится в таблице genreList
2) с лайками то же самое, но для них надо создать дополнительную таблицу для связи многие ко многим для связи юзера и фильма, наличие связи обозначает что лайк есть, отсутствие связи обозначает что лайка нету
3) таблица пользователей, снова лишний поле, друзья должна так же храниться через дополнительную таблицу со связью многие ко многим, где связь будет между таблицей user и таблицей user

2023-03-31 11:58 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return List.copyOf(getAllFilm().stream()
Получение топ 10 фильмов можно и лучше сделать одним отдельным запросом к базе

2023-03-31 11:58 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        userDao.getUserById(userId);
чаще при получении обьекта с уровня хранилища , если такого обьекта нету возвращается null или Optional.empty И уже на уровне сервиса это обрабатывается

2023-03-31 11:58 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        userDao.getUserById(userId);
а при удалении лайка нам не важно есть ли в хранилище такой фильм или пользователь, ведь нам важнее есть ли такая запись

2023-03-31 11:58 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public List<User> commonFriend(Long userId, Long otherId) {
это тоже можно выполнить одним запросом к базе данных, но это будет посложнее (не обязательно выполнять)

2023-03-31 11:58 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public List<User> viewUserFriend(Long userId) {
лучше назвать метод getUserFriends

2023-03-31 11:58 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/implement/FilmLikeDB.java
> +    public Set<Long> userLikeByFilmId(Long filmId) {
не понятно зачем этот метод, если для получения пользователей, то почему бы не сделать join таблицы с пользователями? и не возвращать обьекты пользователей вместо их id

2023-03-31 11:58 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/implement/FilmStorageDB.java
> +        list.forEach(id -> {
1) почему переменная называется id если в ней целиком фильм
2) сейчас при получнии n фильмов будет сделано 1 + n * 2 запросов, необходимо это сделать за 3 запроса

2023-03-31 11:58 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/implement/FilmStorageDB.java
> +            sqlRequest = "SELECT * " +
зачем получать все поля таблицы если можно только id

2023-03-31 11:58 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/implement/FilmStorageDB.java
> +            sqlRequest = "SELECT * " +
второй пункт имена фильмов не уникальны, поэтому может возникнуть ошибка если добавлены два фильма с одним и тем же именем

2023-03-31 11:58 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/implement/FriendStorageDB.java
> +        String sqlQuery = "SELECT friend_id FROM friends WHERE user_id = ?";
запрос не верный, так как если первый пользователь добавил второго в друзья, то при запросе друзей первого второй бьудет у него в друзьях, при запросе друзей второго, первый не будет в его друзьях

2023-04-01 13:30 UTC, MR-k0f31n commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public List<User> viewUserFriend(Long userId) {
сделал

2023-04-01 13:30 UTC, MR-k0f31n commented on DataBase.png
разобрались

2023-04-01 13:31 UTC, MR-k0f31n commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        userDao.getUserById(userId);
проверили

2023-04-01 13:31 UTC, MR-k0f31n commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/implement/FilmLikeDB.java
> +    public Set<Long> userLikeByFilmId(Long filmId) {
какой-то аппендикс - изъяли из тела

2023-04-01 13:53 UTC, MR-k0f31n commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/implement/FriendStorageDB.java
> +        String sqlQuery = "SELECT friend_id FROM friends WHERE user_id = ?";
Разобрались в пачке что запрос верный

2023-04-01 13:53 UTC, MR-k0f31n commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/implement/FilmStorageDB.java
> +        list.forEach(id -> {
ВРОДЕ РАЗОБРАЛСЯ!!!!

2023-04-01 20:31 UTC, TomattmanYandex requested changes
насколько я помню с ревью остался один момент который надо пофиксить

2023-04-01 20:31 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return List.copyOf(getAllFilm().stream()
это надо исправить

2023-04-01 20:31 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/implement/FilmStorageDB.java
> +                "WHERE f.film_id IN (SELECT film_id FROM films ORDER BY film_id ASC)";
не понял зачем это условие ведь и без него должны все вернуться, если правильные джойны использовались

2023-04-02 09:24 UTC, MR-k0f31n commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/implement/FilmStorageDB.java
> +                "WHERE f.film_id IN (SELECT film_id FROM films ORDER BY film_id ASC)";
ага, горе от ума, полностью согласен

2023-04-03 07:33 UTC, TomattmanYandex approved these changes
Принято

2023-04-03 07:33 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/implement/FilmStorageDB.java
> +        String sqlRequest = "WITH cte AS " +
сложно, можно и легче

2023-04-03 11:05 UTC, merged